### ISSUE TITLE
It takes long time to start with sudo

### ISSUE THREAD

**Issue by alex285** [flathub/org.vim.Vim#2] opened 2018-05-14 11:12 UTC
### Reproduce
1. Run Vim
```
flatpak run org.vim.Vim some_file
```
That opens instantly

2. Run Vim with Sudo
```
sudo flatpak run org.vim.Vim some_root_file
```
That takes more than 10 seconds to start. I unset `DBUS_SESSION_BUS_ADDRESS` and still the same issue.

### Other Notices
When I run the same on a TTY it instantly opens
```
sudo flatpak run org.vim.Vim some_root_file
```
So the issue happens only inside the GNOME & Pantheon Sessions I tested

### Versions
Flatpak 0.11.7
Vim: Commit: b351d952a53811593ef525f072505a9b6addf5b2075ff3a8fba7efaa65013631
Fedora Rawhide

### Output
I'm attaching the output
```
sudo flatpak run -v -v org.vim.Vim test_root

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Disallowing network access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running '--ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files /usr --lock-file /usr/.ref --ro-bind /var/lib/flatpak/app/org.vim.Vim/x86_64/stable/b351d952a53811593ef525f072505a9b6addf5b2075ff3a8fba7efaa65013631/files /app --lock-file /app/.ref --tmpfs /usr/lib/GL --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-396-24/x86_64/1.4/7a589121f2b678abb8900d001e4deb0b133b105e9242e6cceb10707115461886/files /usr/lib/GL/nvidia-396-24 --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6/b5f77229b85f1cfb266562b26c3b39221a3db71ea01cf9d2e53d54dbf97578d1/files /usr/lib/ffmpeg --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.Locale/x86_64/1.6/6644cf1b3b7754e046cef707107a36964ebddfcac81b52834eda9512cca81bc5/files /usr/share/runtime/locale --tmpfs /usr/share/runtime/share/themes --ro-bind /var/lib/flatpak/runtime/org.gtk.Gtk3theme.elementary/x86_64/3.22/e6cf5f8fe51837e8af54ed61525c1aeae0682ca1b319d1cd5e70a6b0ee9afc6e/files /usr/share/runtime/share/themes/elementary/gtk-3.0 --bind-data 3 /run/flatpak/ld.so.conf.d/runtime-001-org.freedesktop.Platform.GL.nvidia-396-24.conf --symlink /usr/lib/GL/nvidia-396-24/vulkan/icd.d/nvidia_icd.json /usr/lib/GL/vulkan/icd.d/nvidia_icd.json --symlink /usr/lib/GL/nvidia-396-24/glvnd/egl_vendor.d/10_nvidia.json /usr/lib/GL/glvnd/egl_vendor.d/10_nvidia.json --bind-data 4 /run/flatpak/ld.so.conf.d/runtime-002-org.freedesktop.Platform.ffmpeg.conf --unshare-pid --proc /proc --dir /tmp --dir /var/tmp --dir /run/host --dir /run/user/0 --setenv XDG_RUNTIME_DIR /run/user/0 --symlink ../run /var/run --ro-bind /sys/block /sys/block --ro-bind /sys/bus /sys/bus --ro-bind /sys/class /sys/class --ro-bind /sys/dev /sys/dev --ro-bind /sys/devices /sys/devices --bind-data 6 /etc/passwd --bind-data 7 /etc/group --ro-bind /etc/machine-id /etc/machine-id --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/xdg /etc/xdg --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/rcS.d /etc/rcS.d --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/pulse /etc/pulse --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/fonts /etc/fonts --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/xml /etc/xml --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/issue.net /etc/issue.net --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/ld.so.conf /etc/ld.so.conf --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/ca-certificates.conf /etc/ca-certificates.conf --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/issue /etc/issue --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/pki /etc/pki --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/sysctl.conf /etc/sysctl.conf --symlink /usr/lib/GL/glvnd /etc/glvnd --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/protocols /etc/protocols --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/ld.so.cache /etc/ld.so.cache --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/init.d /etc/init.d --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/timestamp /etc/timestamp --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/nsswitch.conf /etc/nsswitch.conf --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/gtk-3.0 /etc/gtk-3.0 --symlink /usr/lib/GL/OpenCL /etc/OpenCL --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/drirc /etc/drirc --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/ssl /etc/ssl --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/locale.conf /etc/locale.conf --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/geoclue /etc/geoclue --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/ca-certificates /etc/ca-certificates --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/rpm /etc/rpm --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/shells /etc/shells --symlink /proc/mounts /etc/mtab --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/skel /etc/skel --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/version /etc/version --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/terminfo /etc/terminfo --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/hostname /etc/hostname --symlink /usr/lib/GL/vulkan /etc/vulkan --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/pkcs11 /etc/pkcs11 --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/rpc /etc/rpc --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/filesystems /etc/filesystems --symlink ../usr/lib/os-release /etc/os-release --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/services /etc/services --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/vdpau_wrapper.cfg /etc/vdpau_wrapper.cfg --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/dbus-1 /etc/dbus-1 --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/profile /etc/profile --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/default /etc/default --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/inputrc /etc/inputrc --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/motd /etc/motd --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/fstab /etc/fstab --bind /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/1.6/00f1ad6848905e10452e96aee032d76bd8f9225334fa8129a8ac0a6d25d901ae/files/etc/timezone /etc/timezone --bind /root/.var/app/org.vim.Vim/cache /var/cache --bind /root/.var/app/org.vim.Vim/data /var/data --bind /root/.var/app/org.vim.Vim/config /var/config --bind /root/.var/app/org.vim.Vim/cache/tmp /var/tmp --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/bin /bin --symlink usr/sbin /sbin --seccomp 8 --ro-bind /root/.cache/flatpak-monitor /run/host/monitor --symlink /run/host/monitor/localtime /etc/localtime --symlink /run/host/monitor/resolv.conf /etc/resolv.conf --symlink /run/host/monitor/host.conf /etc/host.conf --symlink /run/host/monitor/hosts /etc/hosts --bind-data 13 /etc/ld.so.conf --ro-bind-data 5 /etc/ld.so.cache --file 11 /.flatpak-info --ro-bind-data 14 /.flatpak-info --symlink ../../../.flatpak-info /run/user/0/flatpak-info --bind /root/.cache/doc/by-app/org.vim.Vim /run/user/0/doc --unshare-net --dev /dev --bind /root/.cache/app/org.vim.Vim /run/user/0/app/org.vim.Vim --bind /.autorelabel /.autorelabel --bind /home /home --bind '/lost+found' '/lost+found' --bind /media /media --bind /mnt /mnt --bind /opt /opt --dir /root --dir /root/.local/share/flatpak --dir /root/.var/app --bind /root/.var/app/org.vim.Vim /root/.var/app/org.vim.Vim --bind /srv /srv --bind /usr /run/host/usr --bind /etc /run/host/etc --tmpfs /tmp/.X11-unix --bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X99 --bind-data 16 /run/user/0/Xauthority --bind /run/systemd/journal/socket /run/systemd/journal/socket --bind /run/systemd/journal/stdout /run/systemd/journal/stdout --ro-bind /usr/share/fonts /run/host/fonts --ro-bind /usr/lib/fontconfig/cache /run/host/fonts-cache --tmpfs /run/host/user-fonts-cache --remount-ro /run/host/user-fonts-cache --ro-bind /usr/share/icons /run/host/share/icons --symlink /app/lib/debug/source /run/build --symlink /usr/lib/debug/source /run/build-runtime vim test_root'
```

**Comment by TingPing** [comment] 2018-05-16 11:19
This was discussed on IRC for a bit but you shouldn't ever be running this as root. Use `sudoedit`.

**Comment by alex285** [comment] 2018-05-21 23:19
@TingPing Can you please elaborate a bit on this? We shouldn't run specifically Vim as root, or any CLI Flatpak app, and why?

Also what you mean use sudoedit? That we should set Flatpak VIM on sudoedit?

**Comment by TingPing** [comment] 2018-08-08 12:26
This has host filesystem access, file-forwarding isn't needed.

**Comment by TingPing** [comment] 2018-08-08 12:27
And yes we should probably just add `--filesystem=/tmp` to fix that.

**Comment by wjt** [comment] 2018-08-08 12:43
Well… it would fix the sudoedit problem, but if I'm not using sudoedit, it's still annoying to have to map `/etc/passwd` to `/run/host/etc/passwd` by hand if I want to view it in `org.vim.Vim`.

**Comment by TingPing** [comment] 2018-08-08 16:07
> it's still annoying to have to map /etc/passwd to /run/host/etc/passwd by hand if I want to view it in org.vim.Vim.

Flatpak will never not be sandboxed, sorry thats just how it works.

**Comment by wjt** [comment] 2018-08-08 16:34
With #4, setting `EDITOR=/var/lib/flatpak/exports/bin/org.vim.Vim` is enough to make `sudoedit` use it correctly. `sudo flatpak run ...` taking 30 seconds is not a Vim-specific bug. So I suggest we close this issue.

**Comment by wjt** [comment] 2018-11-16 21:30
Can't reproduce the 25-second delay when running Vim (or the platform, either version) under `sudo` any more. Please reopen if you can, preferably against Flatpak since it was apparently not Vim-specific.

**Closed by wjt** 2018-11-16 21:30 UTC
